name: DBT Pipeline CI/CD

on:
  push:
    branches:
      - main       # Runs on push to main branch
  schedule:
    - cron: "0 2 * * *"  # Daily at 2:00 AM UTC

jobs:
  dbt:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: SQL_PRACTICE
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
